In [1]:
#import librairs and tools
import pandas as pd
from matplotlib import pyplot as plt
import zipfile
from google.colab import drive
import os
import numpy as np
import re
import json
import requests

In [2]:
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
data=pd.read_csv('/content/drive/My Drive/5Mtrees_clN.csv',index_col=0)

<ipython-input-3-a3fc6581f0d6>:1: DtypeWarning: Columns (1,2,9,10,11,13) have mixed types. Specify dtype option on import or set low_memory=False.
  data=pd.read_csv('/content/drive/My Drive/5Mtrees_clN.csv',index_col=0)

In [ ]:
data

,most_recent_observation,most_recent_observation_type,common_name,scientific_name,city,state,longitude_coordinate,latitude_coordinate,location_type,address,condition,native,diameter_breast_height_binned_CM,greater_metro
0,1/19/2016,inventory_date,mexican fan palm,washingtonia robusta,las vegas,nevada,-115.260232,36.293165,green_space,NaN,NaN,introduced,NaN,lasvegas
1,1/19/2016,inventory_date,chilean mesquite,prosopis chilensis,las vegas,nevada,-115.260217,36.293130,green_space,NaN,NaN,introduced,15.24 to 30.48 cm,lasvegas
2,6/19/2015,inventory_date,holly oak,quercus ilex,las vegas,nevada,-115.309233,36.223032,green_space,3250 Metro Academy Way,NaN,introduced,0 to 15.24 cm,lasvegas
3,1/19/2016,inventory_date,chilean mesquite,prosopis chilensis,las vegas,nevada,-115.260182,36.293152,green_space,NaN,NaN,introduced,0 to 15.24 cm,lasvegas
4,1/19/2016,inventory_date,chilean mesquite,prosopis chilensis,las vegas,nevada,-115.260141,36.293117,green_space,NaN,NaN,introduced,0 to 15.24 cm,lasvegas
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5660250,9/18/2020,inventory_date,chanticleer pear,pyrus calleryana,aurora,colorado,-104.828126,39.704749,NaN,NaN,good,introduced,0 to 15.24 cm,auroraco
5660251,9/18/2020,inventory_date,chanticleer pear,pyrus calleryana,aurora,colorado,-104.828111,39.704682,NaN,NaN,good,introduced,0 to 15.24 cm,auroraco
5660253,9/21/2020,inventory_date,swamp white oak,quercus bicolor,aurora,colorado,-104.879154,39.732750,green_space,NaN,fair,introduced,0 to 15.24 cm,auroraco
5660262,9/22/2020,inventory_date,honeylocust,gleditsia triacanthos,aurora,colorado,-104.844097,39.685980,green_space,NaN,poor,introduced,15.24 to 30.48 cm,auroraco
5660263,9/22/2020,inventory_date,cottonwood,populus,aurora,colorado,-104.824442,39.753865,green_space,NaN,good,no_info,15.24 to 30.48 cm,auroraco

In [ ]:
Trees_abundance_by_city=data.groupby("city")["scientific_name"].value_counts()

In [ ]:
Trees_abundance_by_city

city      scientific_name
adair     acer saccharinum          72
          fraxinus pennsylvanica    53
          acer platanoides          27
          picea pungens             22
          acer saccharum            16
                                    ..
woodward  quercus macrocarpa         1
          salix                      1
          sorbus                     1
          thuja occidentalis         1
          tilia                      1
Name: scientific_name, Length: 11919, dtype: int64

In [ ]:
type(Trees_abundance_by_city)

pandas.core.series.Series

In [ ]:
Trees_abundance_by_city.to_json('/content/drive/My Drive/Trees_abundance_by_city.json')

In [ ]:
check_mul_city=data.groupby("city")["state"]

In [ ]:
cities_in_states= data.groupby("state")["city"].unique().apply(list)
#json_data=json.dumps(cities_in_states, indent=4)
cities_in_states.to_json('/content/drive/My Drive/cities_in_states.json')

In [ ]:
first_group = data.groupby(["state","city"])["scientific_name"].value_counts()

In [ ]:
first_group

scientific_name              abelia grandiflora  abies  abies amabilis  \
state      city
arizona    phoenix                            0      0               0
california anaheim                            0      0               0
           fresno                             0      0               0
           garden grove                       0      0               0
           huntington beach                   0      0               0
...                                         ...    ...             ...
wisconsin  west allis                         0      6               0
           west bend                          0      0               0
           west milwaukee                     0      0               0
           whitefish bay                      0      0               0
           wind lake                          0      0               0

scientific_name              abies balsamea  abies borisiiregis  \
state      city
arizona    phoenix                        0                   0
california anaheim                        0                   0
           fresno                         0                   0
           garden grove                   0                   0
           huntington beach               0                   0
...                                     ...                 ...
wisconsin  west allis                     0                   0
           west bend                      0                   0
           west milwaukee                 0                   0
           whitefish bay                  0                   0
           wind lake                      0                   0

scientific_name              abies concolor  abies firma  abies fraseri  \
state      city
arizona    phoenix                        0            0              0
california anaheim                        0            0              0
           fresno                         0            0              0
           garden grove                   0            0              0
           huntington beach               0            0              0
...                                     ...          ...            ...
wisconsin  west allis                     0            0              0
           west bend                      0            0              0
           west milwaukee                 0            0              0
           whitefish bay                  0            0              0
           wind lake                      0            0              0

scientific_name              abies grandis  abies homolepis  ...  \
state      city                                              ...
arizona    phoenix                       0                0  ...
california anaheim                       0                0  ...
           fresno                        0                0  ...
           garden grove                  0                0  ...
           huntington beach              0                0  ...
...                                    ...              ...  ...
wisconsin  west allis                    0                0  ...
           west bend                     0                0  ...
           west milwaukee                0                0  ...
           whitefish bay                 0                0  ...
           wind lake                     0                0  ...

scientific_name              zanthoxylum americanum  \
state      city
arizona    phoenix                                0
california anaheim                                0
           fresno                                 0
           garden grove                           0
           huntington beach                       0
...                                             ...
wisconsin  west allis                             0
           west bend                              0
           west milwaukee                         0
           whitefish bay                          0
           wind lake                              0

scientific_name              zanthoxylum clavaherculis  zanthoxylum fagara  \
state      city
arizona    phoenix                                   0                   0
california anaheim                                   0                   0
           fresno                                    0                   0
           garden grove                              0                   0
           huntington beach                          0                   0
...                                                ...                 ...
wisconsin  west allis                                0                   0
           west bend                                 0                   0
           west milwaukee                            0                   0
           whitefish bay                             0                   0
           wind lake                                 0                   0

scientific_name              zanthoxylum piperitum  zelkova  zelkova serrata  \
state      city
arizona    phoenix                               0        0                0
california anaheim                               0        0              290
           fresno                                0        0              126
           garden grove                          0        0                4
           huntington beach                      0        0               15
...                                            ...      ...              ...
wisconsin  west allis                            0        0                0
           west bend                             0        0                0
           west milwaukee                        0        0                0
           whitefish bay                         0        0                0
           wind lake                             0        0                0

scientific_name              zelkova sinica  ziziphus jujuba  \
state      city
arizona    phoenix                        0                0
california anaheim                        0                0
           fresno                         0                0
           garden grove                   0                2
           huntington beach               0                0
...                                     ...              ...
wisconsin  west allis                     0                0
           west bend                      0                0
           west milwaukee                 0                0
           whitefish bay                  0                0
           wind lake                      0                0

scientific_name              ãƒæ’ã†â€™ãƒâ¢ã¢â€šâ¬ã¢â‚¬âchiranthofremontia lenzii  \
state      city
arizona    phoenix                                                           0
california anaheim                                                           0
           fresno                                                            0
           garden grove                                                      0
           huntington beach                                                  0
...                                                                        ...
wisconsin  west allis                                                        0
           west bend                                                         0
           west milwaukee                                                    0
           whitefish bay                                                     0
           wind lake                                                         0

scientific_name              ãƒæ’ã†â€™ãƒâ¢ã¢â€šâ¬ã¢â‚¬âsycoparrotia p
state      city
arizona    phoenix                                                   0
california anaheim                                                   0
           fresno                                                    0
           garden grove                                              0
           huntington beach                                          0
...                                                                ...
wisconsin  west allis                                                0
           west bend                                                 0
           west milwaukee                                            0
           whitefish bay                                             0
           wind lake                                                 0

[121 rows x 1818 columns]

In [ ]:
first_group.to_json('/content/drive/My Drive/Trees_abundance_by_city1.json')

In [ ]:
import json

In [ ]:
Global_dict={}
for state,state_df in data.groupby("state"):
  state_dict={}
  citiesl=state_df["city"].value_counts().to_dict()
  state_dict["cities"]=list(citiesl.keys())
  for city,city_df in state_df.groupby("city"):
    city_dict={}
    treeandabundace=city_df["scientific_name"].value_counts().to_dict()
    topcities=list(treeandabundace.keys())[0:10]
    topcities_abundance=list(treeandabundace.values())[0:10]
    city_dict["trees"]=topcities
    city_dict["abundances"]=topcities_abundance

    state_dict[city]=city_dict

  Global_dict[state]=state_dict


with open('top10trees_bycity_bystate.json', 'w') as json_file:
    json.dump(Global_dict, json_file, indent=4)

In [ ]:
Global_dict={}
for state,state_df in data.groupby("state"):
  state_dict={}
  citiesl=state_df["city"].value_counts().to_dict()
  state_dict["cities"]=list(citiesl.keys())
  for city,city_df in state_df.groupby("city"):
    city_dict={}
    treeandabundace=city_df["scientific_name"].value_counts().to_dict()
    topcities=list(treeandabundace.keys())[0:10]
    topcities_abundance=list(treeandabundace.values())[0:10]
    city_dict["trees"]=topcities
    city_dict["abundances"]=topcities_abundance

    for scientific_name in topcities:

      top3_cmn=city_df[city_df["scientific_name"]== scientific_name ]["common_name"].value_counts().to_dict()
      top3_cmname=list(top3_cmn.keys())[0:3]

      condition=city_df[city_df["scientific_name"]== scientific_name ]["condition"].value_counts().to_dict()
      cond = list(condition.keys())[0] if not  len(list(condition.keys()))==0 else "nan"


      loc_type=city_df[city_df["scientific_name"]== scientific_name ]["location_type"].value_counts().to_dict()
      loc = list(loc_type.keys())[0] if not len(list(loc_type.keys()))==0 else "nan"


      diameter_breast=city_df[city_df["scientific_name"]== scientific_name ]["diameter_breast_height_binned_CM"].value_counts().to_dict()
      db = list(diameter_breast.keys())[0] if not len(list(diameter_breast.keys()))==0 else "nan"


      city_dict[scientific_name]=(top3_cmname , cond , loc ,db )

    state_dict[city]=city_dict

  Global_dict[state]=state_dict


with open('top10trees_bycity_bystate.json', 'w') as json_file:
    json.dump(Global_dict, json_file, indent=4)

In [ ]:
bsd= data[data["scientific_name"] == "fraxinus"]["condition"].value_counts().to_dict()
list(bsd.keys())[0]

'good'

In [ ]:
hiGlobal_dic={}
for state, state_df in data.groupby("state"):
  state_dict={}
  topsC=state_df.value_counts("city").to_dict()
  topsT=state_df.value_counts("scientific_name").to_dict()
  top10cities=list(topsC.keys())[0:10]
  top6trees=(list(topsT.keys())[0:5])+["others"]
  state_dict["tress"]=top6trees
  state_dict["cities"]=top10cities

  for city, city_df in state_df.groupby("city"):
    city_dict={}
    topsTcity=city_df.value_counts("scientific_name").to_dict()
    totalsum=sum(topsTcity.values())
    included_sum=[]
    if city in top10cities:
      for name in top6trees[0:5]:
        count = topsTcity.get(name,0)
        included_sum.append(count)
        percentage = (count / totalsum) * 100
        city_dict[name]=(count ,( (count/ totalsum)* 100))
    total_in_array=sum(included_sum)
    missing=totalsum-total_in_array
    city_dict["others"]=(missing ,( (missing/ totalsum)* 100))
    state_dict[city]=city_dict
  Global_dic[state]=state_dict

with open('top5trees_by10city_plot2.json', 'w') as json_file:
    json.dump(Global_dic, json_file, indent=4)

In [ ]:
len(data["city"].unique())

121

In [ ]:

for state, state_df in data.groupby("state"):
  qqq=state_df.value_counts("city").to_dict()
  bs=list(qqq.keys())+ ["other"]
  nb=sum(qqq.values())
  print(nb)

212
1462259
353808
167869
121894
14667
15805
44767
32711
104072
120183
1333
90077
83452
31864
2474
772242
22593
135412
8871
216751
40154
61304
10411
246732
1815
164903
115824

the scema should be like this {
{

    "cities": [

        "new york",

        "los angeles",

        "denver",

        "portland",
        
        "san diego",

        "houston",

        "san francisco",

        "washington dc",

        "seattle",

        "columbus"

    ],

    "trees": [

        "platanus acerifolia",

        "lagerstroemia indica",

        "acer platanoides",

        "gleditsia triacanthos",

        "pyrus calleryana",

        "others"

    ],

    "columbus": {

        "pyrus calleryana": [

            9245,

            6.827312202758988

        ],

        "gleditsia triacanthos": [

            7090,

            5.235872743922252

        ],

        "acer platanoides": [

            4549,

            3.359377307771837

        ],

        "platanus acerifolia": [

            3916,

            2.891915044456917

        ],

        "others": [

            110612,

            81.68552270109001

        ]

    },

    .

    .

    .


    }

In [ ]:
Global_dict={}

citiesl=list(data["city"].value_counts().to_dict())[0:10]
Global_dict["cities"]=citiesl

treesl=list(data["scientific_name"].value_counts().to_dict())[0:5]
treesl=treesl + ["others"]
Global_dict["trees"]=treesl

for city,city_df in data.groupby("city"):
  city_dict={}
  treeandabundace=city_df["scientific_name"].value_counts().to_dict()
  tree_names=list(treeandabundace.keys())
  tree_abundance=list(treeandabundace.values())
  totalsum=sum(treeandabundace.values())

  if city in citiesl:
    included_sum=[]
    for name in tree_names:
      count=treeandabundace.get(name,0)
      if name in treesl[0:5]:
        included_sum.append(count)
        city_dict[name]=( count  ,  ( (count/ totalsum)* 100) )
    total_in_array=sum(included_sum)
    missing=totalsum-total_in_array
    city_dict["others"]=(missing ,( (missing/ totalsum)* 100))
    Global_dict[city]=city_dict


with open('top5tress_of_top10cities.json', 'w') as json_file:
    json.dump(Global_dict, json_file, indent=4)

scema:

{

  cities:[top 20 cities here among the dataset]
  trees:[top 20 trees here among the dataset]

  for each city ih the cities list:
    city_name:{
      for each name in trees:
      tree_name:[occurance of this tree in this city]
    }

}

In [ ]:
Global_dict={}

citiesl=list(data["city"].value_counts().to_dict())[:20]
Global_dict["cities"]=citiesl

treesl=list(data["scientific_name"].value_counts().to_dict())[:20]
Global_dict["trees"]=treesl

for city,city_df in data.groupby("city"):
  city_dict={}
  treeandabundace=city_df["scientific_name"].value_counts().to_dict()
  tree_names=list(treeandabundace.keys())
  tree_abundance=list(treeandabundace.values())


  if city in citiesl:
    included_sum=[]
    for name in tree_names:
      count=treeandabundace.get(name,0)
      if name in treesl:
        included_sum.append(count)
        city_dict[name]=( count )


    Global_dict[city]=city_dict


with open('top20tress_of_top20cities.json', 'w') as json_file:
    json.dump(Global_dict, json_file, indent=4)

sankey diagram:

for further information about the scema required and the sankey diagram check here:

https://www.notion.so/Sanky-diagram-f1c81d6e4e8a4d128154858823e6fde4?pvs=4

In [ ]:
Global_dict={}

citiesl=list(data["city"].value_counts().to_dict())[:20]
Global_dict["cities"]=citiesl

treesl=list(data["scientific_name"].value_counts().to_dict())[:20]
Global_dict["trees"]=treesl

for city,city_df in data.groupby("city"):
  city_dict={}
  treeandabundace=city_df["scientific_name"].value_counts().to_dict()
  tree_names=list(treeandabundace.keys())
  tree_abundance=list(treeandabundace.values())


  if city in citiesl:
    included_sum=[]
    for name in tree_names:
      count=treeandabundace.get(name,0)
      if count <1 or count == np.nan or count is None :
        count =0
      if name in treesl:
        included_sum.append(count)
        city_dict[name]=( count )


    Global_dict[city]=city_dict


with open('top20tress_of_top20cities.json', 'w') as json_file:
    json.dump(Global_dict, json_file, indent=4)

In [ ]:
Global_dict = {}
citiesl = list(data["city"].value_counts().to_dict())[:20]
Global_dict["cities"] = citiesl


treesl = list(data["scientific_name"].value_counts().to_dict())[:20]
Global_dict["trees"] = treesl

for state, state_df in data.groupby('state'):
  state_dict={}
  states=[]
  for city in citiesl:
    if city in list(state_df["city"].value_counts().to_dict().keys()):
      state_dict["count"]=data['state'].value_counts().to_dict().get(state,0)
      for city, city_df in state_df.groupby("city"):
          city_dict = {}
          treeandabundance = city_df["scientific_name"].value_counts().to_dict()
          tree_names = list(treeandabundance.keys())
          tree_abundance = list(treeandabundance.values())

          if city in citiesl:
              included_sum = []
              states.append(state)
              city_dict["count"]=state_df['city'].value_counts().to_dict().get(city,0)
              for name in treesl:
                  count = treeandabundance.get(name, 0)
                  if count < 1 or count == np.nan or count is None:
                      count = 0
                  included_sum.append(count)
                  city_dict[name] = count

              state_dict[city] = city_dict
  Global_dict['states']= states
  Global_dict[state]=state_dict

  with open('top20tress_of_top20cities.json', 'w') as json_file:
      json.dump(Global_dict, json_file, indent=4)

In [ ]:
Global_dict = {}
citiesl = list(data["city"].value_counts().to_dict())[:20]
Global_dict["cities"] = citiesl

treesl = list(data["scientific_name"].value_counts().to_dict())[:10]
Global_dict["trees"] = treesl

for state, state_df in data.groupby('state'):
    state_dict = {}
    state_cities = []

    if any(city in citiesl for city in state_df["city"].unique()):
        state_dict["count"] = data['state'].value_counts().to_dict().get(state, 0)

        for city, city_df in state_df.groupby("city"):
            if city in citiesl:
                city_dict = {}
                treeandabundance = city_df["scientific_name"].value_counts().to_dict()

                city_dict["count"] = city_df['city'].value_counts().to_dict().get(city, 0)
                included_sum = []

                for name in treesl:
                    count = treeandabundance.get(name, 0)
                    if count < 1 or count == np.nan or count is None:
                        count = 0
                    included_sum.append(count)
                    city_dict[name] = count

                state_cities.append(city)
                state_dict[city] = city_dict

        if state_cities:
            Global_dict[state] = state_dict


Global_dict['states'] = [state for state in Global_dict.keys() if state not in ['cities', 'trees']]

with open('sankey_data.json', 'w') as json_file:
    json.dump(Global_dict, json_file, indent=4)

In [ ]:
import json
import numpy as np

Global_dict = {}
citiesl = list(data["city"].value_counts().to_dict())[:20]
Global_dict["cities"] = citiesl

treesl = list(data["scientific_name"].value_counts().to_dict())[:10]
Global_dict["trees"] = treesl

for state, state_df in data.groupby('state'):
    state_dict = {}
    state_cities = []

    if any(city in citiesl for city in state_df["city"].unique()):
        state_dict["count"] = state_df[state_df['city'].isin(citiesl)].shape[0]

        for city, city_df in state_df.groupby("city"):
            if city in citiesl:
                city_dict = {}
                treeandabundance = city_df["scientific_name"].value_counts().to_dict()

                city_dict["count"] = city_df.shape[0]
                included_sum = []

                for name in treesl:
                    count = treeandabundance.get(name, 0)
                    #if count < 1 or count == np.nan or count is None:
                     #   count = 0
                    included_sum.append(count)
                    city_dict[name] = count

                state_cities.append(city)
                state_dict[city] = city_dict

        if state_cities:
            Global_dict[state] = state_dict


Global_dict['states'] = [state for state in Global_dict.keys() if state not in ['cities', 'trees']]

with open('sanky_datafl.json', 'w') as json_file:
    json.dump(Global_dict, json_file, indent=4)

In [ ]:
d=open('sanky_data5.json')
data= json.load(d)

In [ ]:
global_dict={"nodes":[],"links":[]}

for state in data["states"]:

  global_dict["nodes"].append({"name":state})

for city in data["cities"]:

  global_dict["nodes"].append({"name":city})

for tree in data["trees"]:

  global_dict["nodes"].append({"name":tree})

for state in data["states"]:
  for city in list(data[state].keys())[1:]:
     global_dict["links"].append({"source": state , "target": city  , "value":str(data[state][city]["count"])  })
     for tree in list(data[state][city].keys())[1:]:
         global_dict["links"].append({"source": city , "target": tree  , "value":str(data[state][city][tree])  })

with open('nodes_links5.json', 'w') as json_file:
    json.dump(global_dict, json_file, indent=4)

In [ ]:
count=data["california"]["los angeles"]["count"]

In [ ]:
f=open("sanky_datafl.json")
data=json.load(f)

In [ ]:
states_northern=["new york", "oregon", "district of columbia","washington", "ohio","maryland","wisconsin", "missouri", "michigan"]


states_southern=["california","colorado", "texas","louisiana","florida"]

In [ ]:
global_dict={"nodes":[],"links":[]}

for state in states_northern:

  global_dict["nodes"].append({"name":state})

x=0
for state in states_northern:
  for city in list(data[state].keys())[1:]:
     global_dict["nodes"].append({"name":city})
     global_dict["links"].append({"source": state , "target": city  , "value":str(data[state][city]["count"])  })
     for tree in list(data[state][city].keys())[1:]:
      if x<10:
         global_dict["nodes"].append({"name":tree})
         global_dict["links"].append({"source": city , "target": tree  , "value":str(data[state][city][tree])  })
         x+=1

      else:
        global_dict["links"].append({"source": city , "target": tree  , "value":str(data[state][city][tree])  })


with open('nodes_links10north.json', 'w') as json_file:
    json.dump(global_dict, json_file, indent=4)

In [ ]:
global_dict={"nodes":[],"links":[]}

for state in states_southern:

  global_dict["nodes"].append({"name":state})

x=0
for state in states_southern:
  for city in list(data[state].keys())[1:]:
     global_dict["nodes"].append({"name":city})
     global_dict["links"].append({"source": state , "target": city  , "value":str(data[state][city]["count"])  })
     for tree in list(data[state][city].keys())[1:]:
      if x<10:
         global_dict["nodes"].append({"name":tree})
         global_dict["links"].append({"source": city , "target": tree  , "value":str(data[state][city][tree])  })
         x+=1

      else:
        global_dict["links"].append({"source": city , "target": tree  , "value":str(data[state][city][tree])  })


with open('nodes_links10south.json', 'w') as json_file:
    json.dump(global_dict, json_file, indent=4)

In [ ]:
s = [
{
            "source": "orlando",
            "target": "lagerstroemia indica",
            "value": "14988"
        },
        {
            "source": "orlando",
            "target": "gleditsia triacanthos",
            "value": "1"
        },
        {
            "source": "orlando",
            "target": "pyrus calleryana",
            "value": "113"
        },
        {
            "source": "orlando",
            "target": "acer rubrum",
            "value": "1814"
        },
        {
            "source": "orlando",
            "target": "fraxinus pennsylvanica",
            "value": "11"
        },
        {
            "source": "orlando",
            "target": "quercus virginiana",
            "value": "17126"
        },
        {
            "source": "orlando",
            "target": "liquidambar styraciflua",
            "value": "284"
        }
      ]

count = 0

for lst in s:
    for key, value in lst.items():
        if key == "value":
            count += int(value)

print(count)

34337

now we want to create data for the line chart, the data of the line chart will display2 line chart one for min and the other for max tempreture for 10 years on the x axis and the tempreture on the y axis, we will generate a line chart for each state that we have in our dataset:
so the work steps are:

>   1.   take the state name that we have in the dataset
    2.   create a new dataset that has state column includes the state we extracted
    3.   extrct tempreture min max and avg from the dataset for each year in this list (2023, 2018, 2013, 2008, 2003, 1998, 1993, 1988, 1983, 1978)
    4.   create coumn for each year so will have

In [ ]:
states=data["state"].unique()

In [37]:
min_apiURL = "https://www.ncei.noaa.gov/pub/data/cirs/climdiv/climdiv-tminst-v1.0.0-20231106"
max_apiURL = "https://www.ncei.noaa.gov/pub/data/cirs/climdiv/climdiv-tmaxst-v1.0.0-20231106"
mean_apiURL= "https://www.ncei.noaa.gov/pub/data/cirs/climdiv/climdiv-tmpcst-v1.0.0-20231106"

In [98]:
def load_transform_data(url, agg_func="mean"):

    datapi = pd.read_table(url, delim_whitespace=True, header=None)

    for i in range(len(datapi[0])):
        if len(str(datapi[0][i])) == 8:
            ds = "00" + str(datapi[0][i])
            datapi.at[i, 0] = ds
        elif len(str(datapi[0][i])) == 9:
            ds = "0" + str(datapi[0][i])
            datapi.at[i, 0] = ds
        elif len(str(datapi[0][i])) == 10:
            datapi.drop(i, inplace=True)

    state = datapi.iloc[:, 0].astype(str).str[:3]
    year = datapi.iloc[:, 0].astype(str).str[-4:]

    if agg_func == "mean":
        variable = datapi.iloc[:, 1:].mean(axis=1)
    elif agg_func == "min":
        variable = datapi.iloc[:, 1:].min(axis=1)
    elif agg_func == "max":
        variable = datapi.iloc[:, 1:].max(axis=1)
    else:
        raise ValueError("Invalid aggregation function. Use 'mean', 'min', or 'max'.")

    my_data = pd.DataFrame({
        "state": state,
        "year": year,
        agg_func: variable
    })

    my_data[agg_func] = my_data[agg_func].astype(int).apply(lambda x: round((x - 32) * 5/9))

    return my_data

In [99]:
datapi2 = pd.read_table(max_apiURL, delim_whitespace=True, header=None)

In [103]:
data_max=load_transform_data(min_apiURL, "min")
data_min=load_transform_data(max_apiURL, "max")
data_mmean=load_transform_data(mean_apiURL, "mean")

In [104]:
data_max

     state  year  max
0      001  1895   32
1      001  1896   34
2      001  1897   34
3      001  1898   33
4      001  1899   33
...    ...   ...  ...
6286   050  2019   19
6287   050  2020   16
6288   050  2021   16
6289   050  2022   17
6290   050  2023   18

[6291 rows x 3 columns]

In [105]:
!git config --global user.name "hussein320"
!git config --global user.email "husseinmaatouk506@gmail.com"
!git config --global user.password "Githubhussein321"

token ="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"
username="hussein320"
repo="5MTREES_D3_DATA_Visualization"

!git clone https://{token}@github.com/{username}/{repo}

Cloning into '5MTREES_D3_DATA_Visualization'...
remote: Enumerating objects: 99, done.
remote: Counting objects: 100% (99/99), done.
remote: Compressing objects: 100% (84/84), done.
remote: Total 99 (delta 57), reused 32 (delta 10), pack-reused 0
Receiving objects: 100% (99/99), 41.08 KiB | 1.87 MiB/s, done.
Resolving deltas: 100% (57/57), done.

In [106]:
%cd {repo}

/content/5MTREES_D3_DATA_Visualization

In [107]:
%ls

data/  LICENSE  my_data/  nodes_links10north.json  README.md

In [108]:
%mkdir line_plot

In [109]:
%cd line_plot

/content/5MTREES_D3_DATA_Visualization/line_plot

In [110]:
%cd ..

/content/5MTREES_D3_DATA_Visualization

In [111]:
%mkdir generate_data

In [112]:
%cd generate_data

/content/5MTREES_D3_DATA_Visualization/generate_data

In [ ]:
%mv